name: Go CI Test Only

on:
  push:
    branches: [main]

jobs:
  test-only:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run HTTP server test
      run: go test ./internal/tests -v
