name: Go CI/CD Pipeline

on:
  push:
    branches: [ "deploy" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      APP_HOST: ${{ secrets.APP_HOST }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./...

    - name: Build app
      run: go build -o app main.go

    - name: Copy app to GCP VM
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: debian
        key: ${{ secrets.GCP_SSH_KEY }}
        source: "app"
        target: "/home/debian/app"

    - name: Restart app on GCP VM
      uses: appleboy/ssh-action@master
      with:Ñ‹
        host: ${{ secrets.GCP_VM_IP }}
        username: debian
        key: ${{ secrets.GCP_SSH_KEY }}
        script: |
          pkill app || true
          nohup ./app > app.log 2>&1 &
